version: 2

machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker info
      - run:
          name: Build docker image
          command: |
            docker build -t flaccid/checks2metrics .
      - deploy:
          name: Push docker image to Docker Hub
          command: |
            docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
            docker push flaccid/checks2metrics
