version: 2

machine:
  services:
    - docker

jobs:
  build:
    working_directory: /go/src/github.com/flaccid/lambstatus-pingdom
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/checks2metrics -a -ldflags '-extldflags "-static"' checks2metrics.go
